### ISSUE TITLE
Splash screen sometimes stays behind

### ISSUE THREAD

**Issue by ajmeese7** [meese-os/meeseOS#150]
I noticed that the splashscreen occasionally lags behind after being made invisible, and it collects all the clicks made to it, preventing any actual interaction with the site. A simple fix is this:

```css
.meeseOS-boot-splash {
  pointer-events: none;
}
```

But I'd need to make sure it is only applied after the splash screen is hidden, otherwise the initial click won't be able to be received on the element to boot up the loading screen.
